import{a as L,S as w,i as b}from"./assets/vendor-C4-ZuMk8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",_="46827902-d0f0ee0995e79e4196197bc56",E=15;async function m(o,r){const n={key:_,image_type:"photo",orientation:"horizontal",safesearch:!0,q:o,page:r,per_page:E};try{return(await L.get(v,{params:n})).data}catch{throw new Error("Failed to fetch images")}}function p(o){return o.map(({webformatURL:r,largeImageURL:n,tags:s,likes:e,views:t,comments:a,downloads:i})=>`<li class="list__item">
            <a href="${n}">
                <img src="${r}" alt="${s}" class="list__image"/>
            </a>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${e}</p>
                <p class="info-item"><b>Views:</b> ${t}</p>
                <p class="info-item"><b>Comments:</b> ${a}</p>
                <p class="info-item"><b>Downloads:</b> ${i}</p>
            </div>
        </li>`).join("")}function g(){new w(".list a",{captionDelay:250,captionsData:"alt"}).refresh()}function u(o){b.error({title:"Error",message:o,position:"topRight"})}function P(o){b.info({title:"Info",message:o,position:"topRight"})}let f=1,y="",h=0,l=0;document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".form"),r=document.querySelector(".list"),n=document.querySelector(".title"),s=document.querySelector(".title_second"),e=document.querySelector(".loadMoreBtn");o.addEventListener("submit",t),e.addEventListener("click",a);async function t(i){i.preventDefault();const d=i.target.elements.search.value.trim();if(!d){u("Please enter a search term!");return}y=d,f=1,r.innerHTML="",n.textContent="Loading images, please wait...",e.classList.remove("visible"),l=0;try{const c=await m(d,f);h=c.totalHits,l+=c.hits.length,c.hits.length===0?u("No images found. Try another search term."):(r.innerHTML=p(c.hits),g(),l<h&&e.classList.add("visible"))}catch{u("Failed to fetch images. Please try again later!")}finally{n.textContent="",i.target.reset()}}async function a(){f+=1,s.textContent="Loading images, please wait...";try{const i=await m(y,f);if(l+=i.hits.length,i.hits.length===0||l>=h)P("We're sorry, but you've reached the end of search results."),e.classList.remove("visible");else{r.insertAdjacentHTML("beforeend",p(i.hits)),g();const c=document.querySelector(".list__item").getBoundingClientRect().height;window.scrollBy({top:c*2,behavior:"smooth"}),s.textContent=""}}catch{u("Failed to fetch images. Please try again later!")}}});
//# sourceMappingURL=index.js.map
