import{a as L,S as b,i as d}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",w="46827902-d0f0ee0995e79e4196197bc56",E=15;async function h(a,o){const s={key:w,image_type:"photo",orientation:"horizontal",safesearch:!0,q:a,page:o,per_page:E};try{return(await L.get(v,{params:s})).data}catch{throw new Error("Failed to fetch images.")}}let u;function p(){u?u.refresh():u=new b(".list a",{captionDelay:250,captionsData:"alt"})}function g(a){return a.map(({webformatURL:o,largeImageURL:s,tags:t,likes:e,views:r,comments:i,downloads:n})=>`<li class="list__item">
            <a href="${s}">
                <img src="${o}" alt="${t}" class="list__image"/>
            </a>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${e}</p>
                <p class="info-item"><b>Views:</b> ${r}</p>
                <p class="info-item"><b>Comments:</b> ${i}</p>
                <p class="info-item"><b>Downloads:</b> ${n}</p>
            </div>
        </li>`).join("")}let f=1,y="",m=0,l=0;document.addEventListener("DOMContentLoaded",()=>{const a=document.querySelector(".form"),o=document.querySelector(".list"),s=document.querySelector("h1"),t=document.querySelector(".loadMoreBtn");a.addEventListener("submit",e),t.addEventListener("click",r);async function e(i){i.preventDefault();const n=i.target.elements.search.value.trim();if(!n){d.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}y=n,f=1,o.innerHTML="",s.textContent="Loading images, please wait...",t.classList.remove("visible"),l=0;try{const c=await h(n,f);m=c.totalHits,l=c.hits.length,l===0?d.error({title:"Error",message:"No images found. Try another search term.",position:"topRight"}):(o.innerHTML=g(c.hits),p(),l<m&&t.classList.add("visible"))}catch{d.error({title:"Error",message:"Failed to fetch images. Please try again later!",position:"topRight"})}finally{s.textContent="",i.target.reset()}}async function r(){f+=1,s.textContent="Loading images, please wait...";try{const i=await h(y,f);if(l+=i.hits.length,i.hits.length>0){o.insertAdjacentHTML("beforeend",g(i.hits)),p();const c=document.querySelector(".list__item").getBoundingClientRect().height;window.scrollBy({top:c*2,behavior:"smooth"})}l>=m?(t.classList.remove("visible"),t.classList.add("hidden"),d.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):(t.classList.add("visible"),t.classList.remove("hidden"))}catch{d.error({title:"Error",message:"Failed to fetch images. Please try again later!",position:"topRight"})}finally{s.textContent="",console.log(t.classList)}}});
//# sourceMappingURL=index.js.map
