import{a as b,S as L,i as d}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",w="46827902-d0f0ee0995e79e4196197bc56",E=15;async function p(a,o){const s={key:w,image_type:"photo",orientation:"horizontal",safesearch:!0,q:a,page:o,per_page:E};try{return(await b.get(v,{params:s})).data}catch{throw new Error("Failed to fetch images.")}}let u;function h(){u?u.refresh():u=new L(".list a",{captionDelay:250,captionsData:"alt"})}function g(a){return a.map(({webformatURL:o,largeImageURL:s,tags:i,likes:e,views:t,comments:r,downloads:n})=>`<li class="list__item">
            <a href="${s}">
                <img src="${o}" alt="${i}" class="list__image"/>
            </a>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${e}</p>
                <p class="info-item"><b>Views:</b> ${t}</p>
                <p class="info-item"><b>Comments:</b> ${r}</p>
                <p class="info-item"><b>Downloads:</b> ${n}</p>
            </div>
        </li>`).join("")}let f=1,y="",m=0,l=0;document.addEventListener("DOMContentLoaded",()=>{const a=document.querySelector(".form"),o=document.querySelector(".list"),s=document.querySelector("h1"),i=document.querySelector(".loadMoreBtn");a.addEventListener("submit",e),i.addEventListener("click",t);async function e(r){r.preventDefault();const n=r.target.elements.search.value.trim();if(!n){d.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}y=n,f=1,o.innerHTML="",s.textContent="Loading images, please wait...",i.classList.remove("visible"),l=0;try{const c=await p(n,f);m=c.totalHits,l=c.hits.length,l===0?d.error({title:"Error",message:"No images found. Try another search term.",position:"topRight"}):(o.innerHTML=g(c.hits),h(),l<m&&i.classList.add("visible"))}catch{d.error({title:"Error",message:"Failed to fetch images. Please try again later!",position:"topRight"})}finally{s.textContent="",r.target.reset()}}async function t(){f+=1,s.textContent="Loading images, please wait...";try{const r=await p(y,f);if(l+=r.hits.length,l>=m)d.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),i.classList.remove("visible");else{o.insertAdjacentHTML("beforeend",g(r.hits)),h();const c=document.querySelector(".list__item").getBoundingClientRect().height;window.scrollBy({top:c*2,behavior:"smooth"})}}catch{d.error({title:"Error",message:"Failed to fetch images. Please try again later!",position:"topRight"})}finally{s.textContent=""}}});
//# sourceMappingURL=index.js.map
